import esbuild from "esbuild";
import fs from "fs";
import { createRequire } from "module";
import path from "path";

const require = createRequire(import.meta.url);
const prod = process.argv.includes("production");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
];

const nodeCoreAliases = new Map([
  ["assert", require.resolve("assert/")],
  ["buffer", require.resolve("buffer/")],
  ["crypto", require.resolve("crypto-browserify")],
  ["path", require.resolve("path-browserify")],
  ["stream", require.resolve("stream-browserify")],
  ["url", require.resolve("url/")],
  ["util", require.resolve("util/")],
]);

const nodeCoreFallbackPlugin = {
  name: "node-core-fallback",
  setup(build) {
    build.onResolve({ filter: /^(assert|buffer|crypto|path|stream|url|util)$/ }, (args) => ({
      path: nodeCoreAliases.get(args.path),
    }));

    build.onResolve({ filter: /^node:(assert|buffer|crypto|path|stream|url|util)$/ }, (args) => ({
      path: nodeCoreAliases.get(args.path.slice("node:".length)),
    }));

    build.onResolve({ filter: /^(fs|http|https|os|process|vm)$/ }, (args) => ({
      path: args.path,
      namespace: "empty-module",
    }));

    build.onResolve({ filter: /^node:(fs|http|https|os|process|vm)$/ }, (args) => ({
      path: args.path.slice("node:".length),
      namespace: "empty-module",
    }));

    build.onLoad({ filter: /.*/, namespace: "empty-module" }, () => ({
      contents: "export default {};",
      loader: "js",
    }));
  },
};

const copyDistFiles = () => {
  const distDir = path.join(process.cwd(), "dist");
  fs.mkdirSync(distDir, { recursive: true });

  for (const file of ["main.js", "manifest.json", "styles.css"]) {
    const src = path.join(process.cwd(), file);
    const dest = path.join(distDir, file);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
      console.log(`Copied ${file} to dist/`);
    }
  }
};

const buildOptions = {
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: "main.js",
  format: "cjs",
  platform: "browser",
  target: "es2018",
  sourcemap: prod ? false : "inline",
  minify: prod,
  treeShaking: true,
  banner: {
    js: banner,
  },
  external,
  inject: ["./esbuild.buffer-shim.js"],
  define: {
    "process.env.DEFAULT_ONEDRIVE_CLIENT_ID": JSON.stringify(
      process.env.DEFAULT_ONEDRIVE_CLIENT_ID || ""
    ),
    "process.env.DEFAULT_ONEDRIVE_AUTHORITY": JSON.stringify(
      process.env.DEFAULT_ONEDRIVE_AUTHORITY || ""
    ),
    "process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
    global: "globalThis",
  },
  plugins: [nodeCoreFallbackPlugin],
  logLevel: "info",
};

if (prod) {
  await esbuild.build(buildOptions);
  copyDistFiles();
} else {
  const context = await esbuild.context(buildOptions);
  await context.watch();
  console.log("Watching for changes...");
}
