const path = require('path');
const fs = require('fs');

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY WEBPACK
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProd = process.argv.includes('--mode=production') || process.argv.includes('--mode') && process.argv[process.argv.indexOf('--mode') + 1] === 'production';

const config = {
  entry: './src/main.ts',
  output: {
    filename: 'main.js',
    path: __dirname,
    libraryTarget: 'commonjs',
  },
  target: 'web',
  externals: {
    obsidian: 'obsidian',
    electron: 'electron',
    '@codemirror/autocomplete': '@codemirror/autocomplete',
    '@codemirror/collab': '@codemirror/collab',
    '@codemirror/commands': '@codemirror/commands',
    '@codemirror/language': '@codemirror/language',
    '@codemirror/lint': '@codemirror/lint',
    '@codemirror/search': '@codemirror/search',
    '@codemirror/state': '@codemirror/state',
    '@codemirror/view': '@codemirror/view',
    '@lezer/common': '@lezer/common',
    '@lezer/highlight': '@lezer/highlight',
    '@lezer/lr': '@lezer/lr',
  },
  resolve: {
    extensions: ['.ts', '.js'],
    fallback: {
      buffer: require.resolve('buffer/'),
      stream: require.resolve('stream-browserify'),
      crypto: require.resolve('crypto-browserify'),
      path: require.resolve('path-browserify'),
      url: require.resolve('url/'),
      util: require.resolve('util/'),
      assert: require.resolve('assert/'),
      process: false,
      vm: false,
      http: false,
      https: false,
      fs: false,
      os: false,
    },
    fullySpecified: false,
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        loader: 'ts-loader',
        options: {
          transpileOnly: true,
        },
      },
    ],
  },
  plugins: [
    new (require('webpack').BannerPlugin)({
      banner,
      raw: true,
    }),
    new (require('webpack').DefinePlugin)({
      'process.env.DEFAULT_ONEDRIVE_CLIENT_ID': JSON.stringify(process.env.DEFAULT_ONEDRIVE_CLIENT_ID || ''),
      'process.env.DEFAULT_ONEDRIVE_AUTHORITY': JSON.stringify(process.env.DEFAULT_ONEDRIVE_AUTHORITY || ''),
      'process.env.NODE_ENV': JSON.stringify(isProd ? 'production' : 'development'),
    }),
    new (require('webpack').ProvidePlugin)({
      Buffer: ['buffer', 'Buffer'],
    }),
    {
      apply: (compiler) => {
        compiler.hooks.afterEmit.tap('CopyToReleased', () => {
          if (isProd) {
            const releasedDir = path.join(__dirname, 'released');
            if (!fs.existsSync(releasedDir)) {
              fs.mkdirSync(releasedDir, { recursive: true });
            }
            const filesToCopy = ['main.js', 'manifest.json', 'styles.css'];
            filesToCopy.forEach(file => {
              const src = path.join(__dirname, file);
              const dest = path.join(releasedDir, file);
              if (fs.existsSync(src)) {
                fs.copyFileSync(src, dest);
                console.log(`Copied ${file} to released/`);
              }
            });
          }
        });
      },
    },
  ],
  mode: isProd ? 'production' : 'development',
  devtool: isProd ? false : 'inline-source-map',
};

module.exports = config;
